from typing import Protocol

from bookshelf.domain.book import Book, BookCore


class BookRepository(Protocol):
    def add(self, book: BookCore) -> Book: ...

    def title_exists(self, title: str) -> bool: ...

    def id_exists(self, book_id: int) -> bool: ...

    def delete(self, book_id: int) -> None: ...

    def update(self, book_id: int, book: BookCore) -> Book: ...
